# Generated by Django 3.0.2 on 2020-01-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rm_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='ROOM TITLE', max_length=50)),
                ('description', models.CharField(default='ROOM DESCRIPTION', max_length=500)),
                ('n_to', models.CharField(max_length=10, null=True)),
                ('s_to', models.CharField(max_length=10, null=True)),
                ('w_to', models.CharField(max_length=10, null=True)),
                ('e_to', models.CharField(max_length=10, null=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('player_ct', models.IntegerField(default=0)),
                ('has_item', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.CharField(default='A simple description of the item', max_length=200)),
                ('category', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameworld.Room')),
            ],
        ),
    ]
