# Generated by Django 3.0.2 on 2020-01-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameworld', '0003_auto_20200123_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
