# Generated by Django 3.0.2 on 2020-01-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameworld', '0003_auto_20200121_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
