# Generated by Django 3.0.2 on 2020-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(default='ROOM TITLE', max_length=50)),
                ('description', models.CharField(default='ROOM DESCRIPTION', max_length=500)),
                ('n_to', models.CharField(max_length=10, null=True)),
                ('s_to', models.CharField(max_length=10, null=True)),
                ('w_to', models.CharField(max_length=10, null=True)),
                ('e_to', models.CharField(max_length=10, null=True)),
                ('x', models.CharField(default=0, max_length=5)),
                ('y', models.CharField(default=0, max_length=5)),
            ],
        ),
    ]
