# Generated by Django 3.0.2 on 2020-01-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameworld', '0002_auto_20200123_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location',
            new_name='room',
        ),
    ]
